### ISSUE TITLE
Help with project structure

### ISSUE THREAD

**Issue by kozel-stas** [Drumber/RemoteLight#32]
Hi,

It is a great application, which do everything which i want to implement) 
Bad, I want to have a different approach which i saw at wiki page.

Per my understanding we have remotelight as main control server. So i want to locate it at my raspberry as single instance and control it via network communication. I saw that project have restapi.
 Is it worked correctly? Is it allow to implement all functionality? How java ui works, is it call remotelight core code directly? Do you have ui client which can connect to remote remotelight server? 

Thanks

**Comment by Drumber** [comment]
Hi, the remotelight-core module can't be used as a standalone application. If you want to control your LEDs connected to an Raspberry Pi you need to install the [RemoteLightServer](https://GitHub.com/Drumber/RemoteLightServer) on it. Then you can download the RemoteLight desktop application on your pc (can be downloaded from this repo) and connect it to the server on your raspberry.
Furthermore, if you want to keep the LEDs running without the need of a pc, you could install [RemoteLightWeb](https://GitHub.com/Drumber/RemoteLightWeb) on the raspberry. It's basically a webserver running independently on your raspberry which you can access via any device over a web browser.

**Comment by kozel-stas** [comment]
"Then you can download the RemoteLight desktop application on your pc (can be downloaded from this repo) and connect it to the server on your raspberry." - So I did it already) Ok, got I, the solution with RemoteLightWeb sounds great.

Also I saw the android application. How is it work? Is it connect via rest API? or is it like standalone application which control led strips, like pc version

**Comment by Drumber** [comment]
The android app depends on the same remotelight-core module that the desktop app and RemoteLightWeb uses. So it is a standalone application. I also planned to add the feature for controlling other RemoteLight instances running on a PC from the android app. But I haven't finished the app yet, because I wanted to recode the entire core module before continuing to work on the app.
This is also the same reason why I haven't updated RemoteLightWeb since a while.
The [new core module](https://github.com/RemoteLight/RemoteLight) will be completely redesigned and therefore I didn't want to put unnecessary work into the app and RLWeb if the new core breaks everything anyway.

If you are interested in the REST API, then have a look at the documentation [here](https://github.com/Drumber/RemoteLight/blob/master/remotelight-restapi/README.md). However, only the desktop app currently includes the Rest API.

**Comment by kozel-stas** [comment]
Ok, Thank you a lot.
"If you are interested in the REST API, then have a look at the documentation here. However, only the desktop app currently includes the Rest API." Yea, I saw it, I made a quick check of code) So I can add it) to Web, it is not an issue for me
