### ISSUE TITLE
How i select a Audio Output?

### ISSUE THREAD

**Issue by TorbenLel** [Drumber/RemoteLight#4]
How do i select an audio output instead of an input?

**Comment by Drumber** [comment]
Hi, if you use Windows: since version [pre0.2.0.9](https://github.com/Drumber/RemoteLight/releases/tag/pre0.2.0.9) you can select a sound output by clicking on "Configure native sound input" in the MusicSync tab. Select WASAPI as service. For Format you have to select the highest samplerate your output device supports (usually 48000Hz). You can leave the bitrate at 16 bits and the channels at 2 if you have stereo speakers.
If you are using Linux, you can set up a loopback using PulseAudio.
For MacOS there are also some loopback programs available.
