### ISSUE TITLE
leds don't do anything

### ISSUE THREAD

**Issue by 4zjata** [Drumber/RemoteLight#9]
I tried remote light after month and now after i set up everything leds don't wanna do anything. leds it self are working, gladiator sketch is loaded, everything seems fine but after selecting effect nothing changes.

**Comment by Drumber** [comment]
Hey, I assume that you have connected the strip correctly to the Arduino (data connected to pin 6 of the Arduino and so on).
Please check the following things:
Did you set the exact same number of LEDs in Glediator Sketch and RemoteLight? The number of LEDs must be set correctly everywhere, otherwise it won't work.
Is the Arduiono output in RemoteLight activated/connected (indicated by the colored border).

If you have checked these two things and it still doesn't work, I would need some more information:
- RemoteLight version
- which Arduino do you use
- which LED strip do you use (WS2812, Apa102, SK6812...)
- power supply for the strip is connected and working?

**Comment by 4zjata** [comment]
Leds (WS2812B) itself are working (tested with neopixel demo) actually i have connect leds to port 1 in Arduino Uno but i changed it on gladiator sketch from 6 to 1 maybe its issue?

**Comment by 4zjata** [comment]
It was my fault changing pin from 1 to 6 fixed everything.

**Comment by Drumber** [comment]
Good to know that it works now, so I close this issue.
